sudo: required
language: rust
rust:
  - nightly
  - beta
  - 1.10.0
  - 1.9.0

before_install:
  - curl --silent --location https://github.com/groonga/groonga/raw/master/data/travis/setup.sh | sh

script:
  - cargo test
