sudo: required
language: rust
rust:
  - nightly
  - beta

before_install:
  - curl --silent --location https://github.com/groonga/groonga/raw/master/data/travis/setup.sh | sh

script:
  - cargo build --verbose
